services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
    networks:
      - network

  kafka:
    container_name: kafka
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=LISTENER_DOCKER://:29092,LISTENER_HOST://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=LISTENER_DOCKER://kafka:29092,LISTENER_HOST://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_DOCKER:PLAINTEXT,LISTENER_HOST:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=LISTENER_DOCKER
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    networks:
      - network

  telegram_parser:
    depends_on:
      - kafka
    build:
      context: ./telegram_parser
    container_name: telegram_parser_container
    ports:
      - "8000:8000"
    networks:
      - network


  database_client:
    depends_on:
      - kafka
    build:
      context: ./db
    container_name: database_client_container
    ports:
      - "8001:8001"
    networks:
      - network

networks:
    network: